spring:
  data:
    redis:
      host: redis-10940.c89.us-east-1-3.ec2.redns.redis-cloud.com
      username: default
      password: FRxCynnhxCBb6UGWq0qNKeEkX17Dl4hl
      port: 10940
      ssl:
        enabled: true
